### ISSUE TITLE
Allow configuration of the BASE_URL

### ISSUE THREAD

**Issue by pnegahdar** [google/generative-ai-js#44] opened 2024-01-27 03:01 UTC
```
const BASE_URL = "https://generativelanguage.googleapis.com";
```

The [BASE_URL](https://github.com/google/generative-ai-js/blob/985e01a0f1629a58287a2c6df71f6c7af91b18fa/packages/main/src/requests/request.ts#L20) is not configurable. 

It'd be helpful to make it so for passthrough proxies as needed. Also useful for testing and mocking out with local listeners if needed.

**Comment by hsubox76** [comment] 2024-03-04 20:08
Duplicate of https://github.com/google/generative-ai-js/issues/25. Feel free to add your comment describing your use cases in that issue, it will help us make the case for it.

**Closed by hsubox76** 2024-03-04 20:08 UTC
Labels: duplicate
